apiVersion: v1
kind: Secret
metadata:
  name: demo-app-key
  labels:
    app.kubernetes.io/name: lifecycle-demo
    app.kubernetes.io/instance: demo
type: Opaque
data:
  APP_KEY: {{ randAlphaNum 32 | b64enc | quote }}
